package com.hallmark.enterprise.integration.papi.hmk_purchases.client.storeinfo;

import org.springframework.cloud.openfeign.FeignClient;

import com.hallmark.enterprise.integration.papi.hmk_purchases.client.store_info_sapi.spec.StoresApi;

/**
 * Feign client for Store Info System API
 *
 * <p>
 * This interface defines the Feign client for accessing the Store Info System API.
 * It extends the StoreApi interface generated by OpenAPI.
 * </p>
 *
 * © 2026 Hallmark. All rights reserved.
 *
 * @author Xtivia Team
 * @since 2026-01-06
 * @version 1.0.0
 */
@FeignClient(
    name = "store-info-sapi",
    configuration = StoreInfoFeignClientConfig.class
)
public interface StoreInfoFeignClient extends StoresApi {

}
