package com.hallmark.enterprise.integration.papi.hmk_purchases.client.orders;

import org.springframework.cloud.openfeign.FeignClient;

import com.hallmark.enterprise.integration.papi.hmk_purchases.client.orders_omni_manh_sapi.spec.OrderApi;

/**
 * Feign client for Orders Omni MANH System API - Order Operations
 *
 * <p>
 * This interface defines the Feign client for accessing order operations in the Orders Omni MANH System API.
 * It extends the OrderApi interface generated by OpenAPI for getting order by order number.
 * Uses OrdersFeignClientConfig with case-insensitive properties to handle camelCase JSON.
 * </p>
 *
 * © 2026 Hallmark. All rights reserved.
 *
 * @author Xtivia Team
 * @since 2026-01-06
 * @version 1.0.0
 */
@FeignClient(
    name = "orders-omni-manh-order-sapi",
    configuration = OrdersFeignClientConfig.class
)
public interface OrdersOmniManhFeignClient extends OrderApi {

}
