package com.hallmark.enterprise.integration.papi.hmk_purchases.client.orders;

import org.springframework.cloud.openfeign.FeignClient;

import com.hallmark.enterprise.integration.papi.hmk_purchases.client.orders_omni_manh_sapi.spec.OrderListEmailApi;

/**
 * Feign client for Orders Omni MANH System API - Order List by Email
 *
 * <p>
 * This interface defines the Feign client for retrieving order history by email address.
 * It extends the OrderListEmailApi interface generated by OpenAPI.
 * </p>
 *
 * © 2026 Hallmark. All rights reserved.
 *
 * @author Xtivia Team
 * @since 2026-01-06
 * @version 1.0.0
 */
@FeignClient(
    name = "orders-omni-manh-orderlist-email-sapi",
    configuration = OrdersFeignClientConfig.class
)
public interface OrderListByEmailFeignClient extends OrderListEmailApi {

}
