package com.hallmark.enterprise.integration.papi.hmk_purchases.client.orders;

import org.springframework.cloud.openfeign.FeignClient;

import com.hallmark.enterprise.integration.papi.hmk_purchases.client.orders_omni_manh_sapi.spec.GetShippingMethodLabelApi;

/**
 * Feign client for Orders Omni MANH System API - Shipping Method Label
 *
 * <p>
 * This interface defines the Feign client for retrieving shipping method labels.
 * It extends the GetShippingMethodLabelApi interface generated by OpenAPI.
 * </p>
 *
 * © 2026 Hallmark. All rights reserved.
 *
 * @author Xtivia Team
 * @since 2026-01-06
 * @version 1.0.0
 */
@FeignClient(
    name = "orders-omni-manh-shipping-method-sapi",
    configuration = OrdersFeignClientConfig.class
)
public interface ShippingMethodLabelFeignClient extends GetShippingMethodLabelApi {

}
