spring.application.name=hmk-purchases-papi
server.port=8080

spring.config.import=optional:aws-secretsmanager:/integrations/hmk-purchases-papi/app

spring.cloud.openfeign.client.config.orders-omni-manh-order-sapi.url=https://services.east.dev.hallmark.com/orders-omni-manh-sapi/v1
spring.cloud.openfeign.client.config.orders-omni-manh-orderlist-phone-sapi.url=https://services.east.dev.hallmark.com/orders-omni-manh-sapi/v1
spring.cloud.openfeign.client.config.orders-omni-manh-orderlist-email-sapi.url=https://services.east.dev.hallmark.com/orders-omni-manh-sapi/v1
spring.cloud.openfeign.client.config.orders-omni-manh-shipping-method-sapi.url=https://services.east.dev.hallmark.com/orders-omni-manh-sapi/v1
spring.cloud.openfeign.client.config.store-info-sapi.url=https://services.east.dev.hallmark.com/store-info-sapi/v1

searchRepo.name=Purchases PAPI
application.source=hmk-purchases-papi

# Jackson Configuration - Exclude empty arrays and null values from JSON output
spring.jackson.default-property-inclusion=non_empty

spring.security.oauth2.client.registration.orders-omni-manh-sapi.client-id=${oauth.client.orders-omni-manh.sapi.client_id}
spring.security.oauth2.client.registration.orders-omni-manh-sapi.client-secret=${oauth.client.orders-omni-manh.sapi.client_secret}
spring.security.oauth2.client.registration.orders-omni-manh-sapi.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.orders-omni-manh-sapi.scope=${oauth.client.orders-omni-manh.sapi.scopes}
spring.security.oauth2.client.provider.orders-omni-manh-sapi.token-uri=${oauth.client.orders-omni-manh.sapi.token_url}

spring.security.oauth2.client.registration.store-info-sapi.client-id=${oauth.client.store-info.sapi.client_id}
spring.security.oauth2.client.registration.store-info-sapi.client-secret=${oauth.client.store-info.sapi.client_secret}
spring.security.oauth2.client.registration.store-info-sapi.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.store-info-sapi.scope=${oauth.client.store-info.sapi.scopes}
spring.security.oauth2.client.provider.store-info-sapi.token-uri=${oauth.client.store-info.sapi.token_url}
