spring.config.import=aws-secretsmanager:/integrations/hmk-purchases-papi/app

spring.cloud.openfeign.client.config.orders-omni-manh-order-sapi.url=http://orders-omni-manh-sapi:8080/orders-omni-manh-sapi/v1
spring.cloud.openfeign.client.config.orders-omni-manh-orderlist-phone-sapi.url=http://orders-omni-manh-sapi:8080/orders-omni-manh-sapi/v1
spring.cloud.openfeign.client.config.orders-omni-manh-orderlist-email-sapi.url=http://orders-omni-manh-sapi:8080/orders-omni-manh-sapi/v1
spring.cloud.openfeign.client.config.orders-omni-manh-shipping-method-sapi.url=http://orders-omni-manh-sapi:8080/orders-omni-manh-sapi/v1
spring.cloud.openfeign.client.config.store-info-sapi.url=http://store-info-sapi:8080/store-info-sapi/v1
